#
# Main configuration for BukkitBedrock
#

###--------------------------------###
### G E N E R A L  S E T T I N G S ###
###--------------------------------###

# The name of the message file to use when this plugin is in use.
# This cannot have the file extension attached to the end.
language-file: "messages-en-us"

# Whether to have the debug messages printed to console
debug: false

###--------------------------------###
### C O M M A N D  S E T T I N G S ###
###--------------------------------###

### All settings related to the afk command.
afk:
  ### What should the message look like when going afk?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD
  ###
  ### Comment out to use format set by the language file. Set to %none% to disable
  #away-format: "&7* &a{USERNAME}&7 is now afk via my custom away message."

  ### What should the message look like when going afk when more info is specified?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD, REASON
  ### Comment out to use format set by the language file. Set to %none% to disable
  #away-more-info-format: "&7* &a{USERNAME}&7 is now afk via my custom away message. &o[{REASON}]"

  ### What should the message look like when going un-afk?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD
  ###
  ### Comment out to use format set by language file. Set to %none% to disable
  #back-format: "&7* &a{USERNAME}&7 is no longer afk via my custom back message."

  ### Do you want players to be able to specify why they are away?
  ###
  ### If true, users will be able to specify a reason as to why they're afk.
  ### If the user specifiys a reason, the away-more-info-format key will be used
  ### to announce.
  ###
  ### Default is false.
  allow-more-info: false

### All settings related to the gamemode command.
gamemode:

  ### Should each gamemode have its own permission?
  ###
  ### If true, whenever a gamemode is being set, the user will be checked if they
  ### have permission to set the specific gamemode
  ###
  ### Default is true.
  gamemode-specific-permissions: true

### All settings related to the speed command
speed:
  ### Should each speed type have its own permissions? (walking/flying)
  ###
  ### If true, whenever a speed is set the user will be checked if they have the
  ### permission to change that specific speed type
  ###
  ### Default is true
  speed-type-permissions: true

  ### Should users with this permission be able to bypass maximum speed restrictions?
  ###
  ### If true, users with this permission will be able to set their speed higher
  ### than the set max speed
  ###
  ### Default is false
  max-speed-bypass-permission: false

  ### Should users with this permission be able to bypass minimum speed restrictions?
  ###
  ### If true, users with this permission will be able to set their speed lower
  ### than the set min speed
  ###
  ### Default is false
  min-speed-bypass-permission: false

  ### What is the max walk speed we want users to have?
  ###
  ### A float between 0 and 10. This is the max walk speed able to be set.
  ### If the amount being set is higher than this, it will be set to this value.
  ###
  ### Default is 10
  max-walk-speed: 10.0

  ### What is the min walk speed we want the users to have?
  ###
  ### A float between -10 and 10. This is the min walk speed able to be set.
  ### If the amount being set is lower than this, it will be set to this value.
  ###
  ### Default is -10
  min-walk-speed: -10

  ### What is the max fly speed we want users to have?
  ###
  ### A float between 0 and 10. This is the max fly speed able to be set.
  ### If the amount being set is higher than this, it will be set to this value.
  ###
  ### Default is 10
  max-fly-speed: 10.0

  ### What is the min fly speed we want the users to have?
  ###
  ### A float between -10 and 10. This is the min fly speed able to be set.
  ### If the amount being set is lower than this, it will be set to this value.
  ###
  ### Default is -10
  min-fly-speed: -10

  ### Should the user be allowed to set their speed below 0?
  ###
  ### If true, users will be able to set their speed below 0.
  ###
  ### Default is true
  allow-negative-speed: true

  ### If negative speed is allowed, should the users be required to have
  ### a specific permission in order to access it?
  ###
  ### If true, the users will be checked if hey have permission to set their
  ### speed below 0.
  ###
  ### Default is true
  negative-permission: true

###
nick:

  ### What characters should be able to be used in a nickname?
  ###
  ### This value accepts regular expressions. If the regular expression is
  ### invalid, the value will default to the regular Minecraft username pattern
  ###
  ### Default is "([0-z]\w+)"
  character-whitelist: "([0-z]\w+)"


  inverse-whitelist: false

  allow-chatcolor: true

  chatcolor-permission: true

  maxlength: 16

  allow-reuse: false

  reuse-permission: true