#
# Main configuration for BukkitBedrock
#

###--------------------------------###
### G E N E R A L  S E T T I N G S ###
###--------------------------------###

# The name of the message file to use when this plugin is in use.
# This cannot have the file extension attached to the end.
language-file: "messages-en-us"

# Whether to have the debug messages printed to console
debug: false

###--------------------------------###
### C O M M A N D  S E T T I N G S ###
###--------------------------------###

### All settings related to the afk command.
afk:
  ### What should the message look like when going afk?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD
  ###
  ### Comment out to use format set by the language file. Set to %none% to disable
  #away-format: "&7* &a{USERNAME}&7 is now afk via my custom away message."

  ### What should the message look like when going afk when more info is specified?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD, REASON
  ### Comment out to use format set by the language file. Set to %none% to disable
  #away-more-info-format: "&7* &a{USERNAME}&7 is now afk via my custom away message. &o[{REASON}]"

  ### What should the message look like when going un-afk?
  ###
  ### Supported keywords:
  ### USERNAME, DISPLAYNAME, BLOCKX, BLOCKY, BLOCKZ, WORLD
  ###
  ### Comment out to use format set by language file. Set to %none% to disable
  #back-format: "&7* &a{USERNAME}&7 is no longer afk via my custom back message."

  ### Do you want players to be able to specify why they are away?
  ###
  ### If true, users will be able to specify a reason as to why they're afk.
  ### If the user specifiys a reason, the away-more-info-format key will be used
  ### to announce.
  ###
  ### Default is false.
  allow-more-info: false

### All settings related to the gamemode command.
gamemode:

  ### Should each gamemode have its own permission?
  ###
  ### If true, whenever a gamemode is being set, the user will be checked if they
  ### have permission to set the specific gamemode
  ###
  ### Default is true.
  gamemode-specific-permissions: true